### PR TITLE
widget html text

### PR DESCRIPTION
**Pull request by aurelijusrozenas**
Updated widgets to display textarea instead of input and let html tags inside: Our focus - text, Testimonials - text, Our team - position, description.
Inspired by: wordpress.org/support/topic/zerif-widgets-html-in-text

### CODE REVIEW

**Comment by infro42** [comment]
Not sure why so many commits are here, created different PR with prodcution branch: https://github.com/Codeinwp/zerif-lite/pull/108

**Comment by ineagu** [comment]
@aurelijusrozenas it shows this because you are trying to merge the production branch to development. I mean you did the fix on your PR - production and now you are trying to commit to development :)

**Comment by aurelijusrozenas** [comment]
hmm. Why on earth your development branch would not be up to date with production? OK, I will make another PR.

**Comment by ineagu** [comment]
is updated, but the production branch have just the merged pull requests from dev commits, is not a big deal, is just easier to commit on dev, pull request dev and we can after merge to prod.

**Pull request closed without merging**
