### PR TITLE
WPForms notice + remove Fagri notice #673

### PR DESCRIPTION
**Pull request by radu-themeisle**
- Added notice for WPForms in About page -> Useful plugins
- styled WPForms to look lie Pirate Forms on front page
- Removed notice for Fagri #678

### CODE REVIEW

**Comment by cristian-ungureanu** [comment]
@radu-themeisle , somehow you reverted your work. You did all the job here https://github.com/Codeinwp/zerif-lite/pull/683/commits/038bc7a7af3b0903c1e22db1b2a3bc6e52b20ba9 then you changed it back here https://github.com/Codeinwp/zerif-lite/pull/683/commits/0eb6f6bcb8bc9b0fbf9d4d8397bc6bd257175bfa , please have another look and make sure everything is in its place.

**Comment by radu-themeisle** [comment]
Initially I replaced everywhere Pirate Forms with WPForms Lite but then @rodica-andronache pointed out that Zerif contact form is based on Pirate Forms and styled specifically so we should not remove it, that's why I reverted everything I did, in order to go back to the starting point.
After that, the goal was to only recommend WPForms (we dediced to put it in the "Useful Plugins" tab in about page) and make the form look as close as possible to the Pirate Forms one, although the user has to manually configure field widths in order to get it 100% accurate.

**Comment by ineagu** [comment]
there is some confusion in the notice implementation: https://www.dropbox.com/s/vo1q7akzss7sorx/Screenshot%202018-08-27%2023.07.42.png?dl=0 and we shouldn't proceed like this.

Not sure about the discussion and why we would have 2 paragraphs, just some feedback:

1. "Zerif Lite changes its name and is no longer maintained" can be Zerif lite changes its name and will be no longer maintained, is safer.

2.  Most important, we should not use: admin_url( 'theme-install.php?theme=neve' ) , we can't know if until then the theme will be on w.org under this name. We should use a url that we can control/redirect like themeisle.com/something/ or themeisle.com/themes/neve/?notice=1 for example.

cc @selul

**Comment by cristian-ungureanu** [comment]
Closed this and reopened here https://github.com/Codeinwp/zerif-lite/pull/684

**Pull request closed without merging**
