### PR TITLE
Escaping.

### PR DESCRIPTION
**Pull request by ioanrobciuc**

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@robciucioan 

I don't think hard coded links like that should be escaped: 
<?php echo esc_url( 'http://themeisle.com/themes/zerif-pro-one-page-wordpress-theme/' ); ?>

Also, we allow html tags on certain options, like the phone number in the footer for example. This is how it looks escaped now: http://prntscr.com/9hmtrg
I think it should be used wp_kses() instead of esc_html

**Comment by robciucioan** [comment]
@rodica-andronache, I added "wp_kses_post()" instead of "esc_html()".

Regarding hardcoded links. What is the problem if the links are escaped?

https://github.com/WordPress/twentysixteen/blob/master/footer.php#L51

**Comment by rodica-andronache** [comment]
@robciucioan we also alow html here: http://prntscr.com/9jdb9a

**Comment by robciucioan** [comment]
@rodica-andronache, ok. I will fix today.

**Comment by robciucioan** [comment]
@rodica-andronache, am modificat.

**Pull request merged**
