### PR TITLE
Change social links in zerif_team_widget

### PR DESCRIPTION
**Pull request by spelcaster**
- Adding the class zerif_social_link;
- Refactoring social links in zerif_team_widget class;
- Fix bug in 'Our team section widget' where link field disappears from the form if the user saves it empty;
- Added the method setSocialLinks in zerif_team_widget that allow child themes to modify the widget;

### CODE REVIEW

**Comment by spelcaster** [comment]
Overriding social links in child theme

```php
// paste it to functions.php in your child theme
add_action('wp_register_sidebar_widget', 'set_child_our_team_social_links');
function set_child_our_team_social_links($widget)
{
    if ($widget['classname'] != "widget_zerif_team-widget") {
        return;
    }

    $child_social_links = array(
        'ln_link' => new zerif_social_link("ln_link", "Linkedin link", "fa-linkedin"),
        'gh_link' => new zerif_social_link("gh_link", "Github link", "fa-github"),
        'fb_link' => new zerif_social_link("fb_link", "Facebook link", "fa-facebook"),
        'tw_link' => new zerif_social_link("tw_link", "Twitter link", "fa-twitter"),
    );

    $widget['callback'][0]->setSocialLinks($child_social_links);
}
```

If you know a better way, please share ;P

**Comment by spelcaster** [comment]
I took some social links from https://github.com/Codeinwp/zerif-lite/pull/275

**Comment by rodica-andronache** [comment]
Hi @spelcaster ,

Thank you so much for contacting us and your contribution. I just tried to test your code and got some notices http://prntscr.com/cbmac9 like " Notice: Undefined index: be_link in C:\wamp64\www\wordpress\wp-content\themes\zerif-lite\functions.php on line 1162"

Did you test your code also with some old values in the database to see if there are compatible?
Please let me know this, and if I can help you with anything else.

Regards,
Rodica

**Comment by spelcaster** [comment]
Hi @rodica-andronache,

I guess I know exactly where the problem is and that's not difficult to fix.
I'll check as soon as I get home.

Regards,
Hugo do Carmo.

**Comment by spelcaster** [comment]
Hi again @rodica-andronache,

The bug ocurred because the default widgets were using 'bh_link' as the element id for behance link, and I've had registered this social link as 'be_link'. 
I'm pretty sure that the commit 0169bdd1866fdbabc59383da8a00e344ee2d09f8 should fix the warning.

Regards,
Hugo do Carmo.

**Comment by spelcaster** [comment]
I'm still intrigued with the warning, because if the link is not registered in zerif_team_widget::$social_links, then it should not try to render the link.
My guess is that there's a cache problem associated with this bug in specific.

**Comment by rodica-andronache** [comment]
Hi @spelcaster ,

Sorry for the late answer here. I just tested again and the notices are still there http://prntscr.com/cfy1li also in customize http://prntscr.com/cfy1qo.
I couldn't manage to find a solution yet, but I will try to have a better look in the next days.

Regards,
Rodica

**Comment by spelcaster** [comment]
Hi @rodica-andronache,

I'm running this code in my development environment and I can't reproduce the issue.
My environment:
- O.S.: Arch Linux;
- PHP v7.0.9;

Could you check the PHP error log? It should give us some hints from where this issue is hiding :)

Thanks in advance,
Hugo do Carmo.

**Comment by ineagu** [comment]
@rodica-andronache news here ?

**Pull request closed without merging**
