### PR TITLE
Changes due to accessibility issues: missing labels, text inside links...

### PR DESCRIPTION
**Pull request by felixzapata**
I´ve uploaded some changes due to accessibility issues:
- add text inside social links.
- add focus to see our team information when you use the tab key.
- modify read more links inside latest news.
- modify background colours due to contrast issues.
- modify styles to add focus when you use the tab key.
- replace default `alt` attribute with the `alt` loaded from WordPress multimedia section.
- add text inside detail links in our focus section.
- add missing labels for inputs inside about us section.

### CODE REVIEW

**Comment by rodica-andronache** [comment]
Hi @felixzapata ,

Thank you for your contribution. In order to test this, we would need the pull request to be created from the development branch. We work on development, and if everything is ok, we move it on production.

Regards,
Rodica

**Comment by felixzapata** [comment]
@rodica-andronache done

**Comment by rodica-andronache** [comment]
Hi @felixzapata ,

Thank you so much for the contribution. It will be available in the next update.

Regards,
Rodica

**Comment by felixzapata** [comment]
@rodica-andronache you´re welcome. Maybe we will send another pull request with more changes related with the accessibility. Some of them about the menu in small screens.

**Pull request merged**
