### PR TITLE
Create wpglobus-config.json

### PR DESCRIPTION
**Pull request by tivnet**
Configuration file for multilingual Customizer with WPGlobus.
See http://www.wpglobus.com/documentation/how-to-translate-strings-in-wordpress-customizer/

@ineagu Here is the PR, Ionut. Thank you!

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@tivnet thank you for contributing to Zerif Lite! We'll check this and merge the pull request in the next days.

**Comment by tivnet** [comment]
@rodica-andronache Thank you, here is a screenshot of what you should see if you install the (WPGlobus plugin)[https://wordpress.org/plugins/wpglobus/] and check it with Zerif:

http://screencast.com/t/q6JDhIFNBOj

(I'll be able to make a similar config for the Parallax One, too)

BTW, if you can contribute Romanian .PO file for WPGlobus, we'll be glad to use it and to mention you (with a link) on WP-org readme.txt - special thanks for that.

**Comment by rodica-andronache** [comment]
@tivnet Hey! I tried to test this, but I can't seem to manage to do this. I installed the plugin and followed the steps, but this is what I get for each string http://prntscr.com/8vhz7a

**Comment by tivnet** [comment]
@rodica-andronache 

There was one more step in setup:

- Install https://wordpress.org/plugins/wpglobus-translate-options/
- Tell is to translate Zerif's theme mods

wpglobus-translate-options

**Comment by rodica-andronache** [comment]
@tivnet thanks :)

**Comment by rodica-andronache** [comment]
@tivnet sure, will try to contribute to the .PO file for WPGlobus :)

**Comment by tivnet** [comment]
@rodica-andronache Great! PR the .po to https://github.com/WPGlobus/WPGlobus. Thank you!

**Pull request merged**
