### PR TITLE
Updated about us section to be display in col-lg 4, 6 or 12 depending on what texts are set.

### PR DESCRIPTION
**Pull request by aurelijusrozenas**
Updated about us section to be display in col-lg 4, 6 or 12 depending on what texts are set.

P.S. you should set your IDE or text editor settings to use \n new line separator as a default.

### CODE REVIEW

**Comment by ineagu** [comment]
@rodica-andronache check this out too

**Comment by rodica-andronache** [comment]
@aurelijusrozenas Thank you for your contributions :)

**Comment by aurelijusrozenas** [comment]
Sure. But if you could look at these issues, it would be great: https://github.com/Codeinwp/zerif-lite/issues/141 https://github.com/Codeinwp/zerif-lite/issues/117

**Comment by aurelijusrozenas** [comment]
And more importantly: https://github.com/Codeinwp/zerif-lite/issues/145
pretty please :)

**Comment by rodica-andronache** [comment]
@aurelijusrozenas sorry for the late answer :) I will check it in a couple of days

**Pull request merged**
