### PR TITLE
Keyboard navigation on child links (main menu)

### PR DESCRIPTION
**Pull request by TonyArchambeau**
Adaptation to make sure the child links on the main menu are accessible with keyboard navigation.
- Add some sentance on the .pot and .po files.

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@TonyArchambeau here you did a mistake and send a pull request from production to development, can you also please make it from development?

**Comment by TonyArchambeau** [comment]
Hi. I'm sorry, I don't get it since Github told me: "Codeinwp:development is up to date with all commits from TonyArchambeau:development."
Is this normal? What should I do?
Sorry again.

**Comment by rodica-andronache** [comment]
@TonyArchambeau the pull request should be from development to development. Right now is from TonyArchambeau:production. Here is a screenshot: http://prntscr.com/8f3s1m

**Comment by TonyArchambeau** [comment]
Ok, thanks. I've been working on "master" since the beginning. Is this ok if I do a pull request from my master branch into your dev branch?
If ok, I already made the pull request, you juste have to accept it.

**Pull request closed without merging**
