### PR TITLE
!!!Added SiteOrigin Styles

### LINKED ISSUE #477: Our Team member description hide after click on mobile
On mobile when clicking the team member it brings down their description, clicking the area again should maybe hide the description back if someone on mobile wants to see the team member picture again without having to click out of the page @rodica-andronache a user requested this

### PR DESCRIPTION
**Pull request by UVLabs**
Also renamed full width no title template file display name. Fixes #477 in Zerif Pro, will submit pull request for zerif pro also @rodica-andronache @claudiuvertistudio

### CODE REVIEW

**Comment by ineagu** [comment]
reminder here

**Comment by rodica-andronache** [comment]
@UVLabs it seems ok.
The only problem I see is with this:
 `.siteorigin-panels .widget li::before {
	display: none;
}`

I don't think it's ok to remove that, because the user may want to add a list in one of the widgets http://prntscr.com/bsuq74

Also this 
`.siteorigin-panels article.hentry{
	margin-bottom: 0;
	padding-bottom: 0;
	border-bottom: none;
}

.siteorigin-panels .hentry {
	margin: 0;
}`

should be just one rule

**Comment by rodica-andronache** [comment]
@UVLabs please don't forget about this, on both zerif lite and pro, when you have time :)

**Comment by UVLabs** [comment]
@rodica-andronache I can submit a pull request that will only target the pixels on the images but the following part of the pull request I can't remember what I was doing which made me come up with those styles but I know they are needed:

`.siteorigin-panels article.hentry{
margin-bottom: 0;
padding-bottom: 0;
border-bottom: none;
}

.siteorigin-panels .hentry {
margin: 0;
}`

I also think there's a reason the two snippets aren't joined, I just can't remember how to reproduce the issue which caused me to come up with those two blocks of styes.

**Comment by UVLabs** [comment]
Let me know how to continue here

**Pull request merged**
